-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.price * bs.SALES) as TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES bs
ON bs.BOOK_ID = b.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') LIKE '2022-01'
GROUP BY 1,3
ORDER BY 1,3 desc
