-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as 'SALES_DATE', PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ((SELECT ONLINE_SALE_ID,USER_ID,PRODUCT_ID,SALES_AMOUNT, SALES_DATE
     FROM ONLINE_SALE )
UNION
(SELECT OFFLINE_SALE_ID,null USER_ID,PRODUCT_ID,SALES_AMOUNT, SALES_DATE
FROM OFFLINE_SALE)) AS abc

WHERE SALES_DATE LIKE '2022-03%'
ORDER BY 1,2,3

