-- 코드를 입력하세요
SELECT fp.PRODUCT_ID,fp.PRODUCT_NAME, sum(fp.PRICE * fo.AMOUNT) as 'TOTAL_SALES'
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo
ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') LIKE '2022-05'
GROUP BY 1
ORDER BY 3 desc, 1

