-- 코드를 입력하세요
SELECT uu.USER_ID, uu.NICKNAME, sum(ub.price)
FROM USED_GOODS_BOARD ub
JOIN USED_GOODS_USER uu
ON uu.USER_ID = ub.WRITER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY ub.WRITER_ID
HAVING sum(ub.price) >= 700000
ORDER BY 3