-- 코드를 입력하세요
SELECT DISTINCT cc.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR cc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
ON cc.CAR_ID = ch.CAR_ID
WHERE DATE_FORMAT(ch.START_DATE, '%m') LIKE '10' 
AND cc.CAR_TYPE LIKE '세단'
ORDER BY cc.CAR_ID desc